language: c

addons:
  apt:
    packages:
    - bison
    - flex
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - texinfo
    - grub-pc-bin
    - xorriso

cache:
  directories:
  - $HOME/dennix-toolchain

env:
  - ARCH=i686
  - ARCH=x86_64

before_install:
- unset CC CXX
- export PATH="$HOME/dennix-toolchain/bin:$PATH"
install: make install-toolchain
script: make

notifications:
  irc:
    channels:
    - chat.freenode.net#dennix
    template:
    - "%{author} committed %{commit} \"%{commit_subject}\" on %{branch}."
    - "Changes: %{compare_url}"
    - "%{message} Duration: %{duration} (%{build_url})"
    skip_join: true
